data_path: "trajectories/10Hz/all_joints"
GP:
  model_path: "/home/titta/Documents/rpw/RL_Project/saved_models/all_joints_500iter.pth"
  iterations: 116
RL:
  train_fresh_GP: false
  trials: 1
  iterations: 100
  learning_rate: 0.1
  
  
  
