train_path: "trajectories/100Hz/all_joints/trajectory22.csv"
test_path: "trajectories/100Hz/all_joints/trajectory21.csv" 
data_directory: "trajectories/100Hz/all_joints"
model_path: "trained_models/three_joints_GP.pth"
num_tasks: 5
ard_num_dims: 6
training_iter: 150
train_GP: true
learning_rate: 0.1
state_dim: 1
control_dim: 1
Tf: 30
dt: 0.1 
trials: 10
rl_training_iter: 100
rl_learning_rate: 0.1
